apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gin-is-fun
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gin-is-fun
    spec:
      containers:
      - name: gin-is-fun
        image: gin-is-fun:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: gin-is-fun
spec:
  type: NodePort
  selector:
    app: gin-is-fun
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
